
import { MenuItem } from './types';

export const INITIAL_MENU: MenuItem[] = [
  {
    id: '1',
    name: 'Nasi Lemak Ayam Berempah',
    description: 'Fragrant coconut rice served with crispy spiced fried chicken, sambal, anchovies, peanuts, and cucumber.',
    price: 15.90,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1588675646184-f5b0b0b0b2de?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '2',
    name: 'Char Kway Teow',
    description: 'Stir-fried flat rice noodles with prawns, cockles, chinese sausage, and beansprouts with a smokey breath of wok.',
    price: 12.50,
    category: 'Noodles',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '8',
    name: 'Beef Rendang (Slow Cooked)',
    description: 'Tender beef chunks slow-cooked in a rich coconut milk and spice paste until the sauce is caramelized and dry.',
    price: 18.90,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1623961988350-66b064faf29f?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '9',
    name: 'Mee Goreng Mamak',
    description: 'Spicy stir-fried yellow noodles with tofu, potatoes, eggs, and bean sprouts, flavored with a secret squid sambal.',
    price: 11.50,
    category: 'Noodles',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '3',
    name: 'Satay Ayam (10 Sticks)',
    description: 'Grilled chicken skewers served with traditional peanut sauce, cucumber, and onions.',
    price: 18.00,
    category: 'Appetizer',
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '10',
    name: 'Nasi Kerabu Ayam Percik',
    description: 'Blue-tinted rice served with grilled chicken topped with spiced coconut milk sauce and fresh local herbs.',
    price: 17.50,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1619445101683-11b9338600a7?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '4',
    name: 'Roti Canai with Dhal',
    description: 'Flaky Malaysian flatbread served with aromatic lentil curry.',
    price: 4.50,
    category: 'Breakfast/Snack',
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '5',
    name: 'Laksa Sarawak',
    description: 'Authentic Sarawakian rice vermicelli in a spicy prawn-based broth with shredded chicken and omelette strips.',
    price: 14.50,
    category: 'Noodles',
    image: 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '11',
    name: 'Cendol Durian',
    description: 'Shaved ice dessert with green rice flour jellies, coconut milk, and palm sugar, topped with creamy durian.',
    price: 8.50,
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1590080876351-941da3579cf6?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '6',
    name: 'Teh Tarik',
    description: 'Classic Malaysian pulled milk tea, frothy and sweet.',
    price: 3.50,
    category: 'Beverage',
    image: 'https://images.unsplash.com/photo-1594285481037-25a073f1a53c?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '7',
    name: 'Sirap Bandung',
    description: 'Rose syrup mixed with evaporated milk, served chilled.',
    price: 4.00,
    category: 'Beverage',
    image: 'https://images.unsplash.com/photo-1513244762241-073010b985f5?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  },
  {
    id: '12',
    name: 'Milo Ais Kaw',
    description: 'Super-strength iced chocolate malt drink, a Malaysian childhood favorite.',
    price: 4.50,
    category: 'Beverage',
    image: 'https://images.unsplash.com/photo-1544145945-f904253d0c71?auto=format&fit=crop&q=80&w=800',
    isAvailable: true,
  }
];

export const CATEGORIES = ['All', 'Main Course', 'Noodles', 'Appetizer', 'Breakfast/Snack', 'Dessert', 'Beverage'];
export const FALLBACK_IMAGE = 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400';
